services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-countrydb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin123!
      - MSSQL_PID=Developer
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - country-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Admin123!" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  mssql_data:
    driver: local

networks:
  country-network:
    driver: bridge
